- Unholy/Assets/Scenes/gang.meta
- Unholy/Assets/Scenes/gang/Prefabs.meta
- Unholy/Assets/Scenes/gang/Prefabs/Monster.prefab
- Unholy/Assets/Scenes/gang/Prefabs/Monster.prefab.meta
- Unholy/Assets/Scenes/gang/Scenes.meta
- Unholy/Assets/Scenes/gang/Scenes/Monster.unity
- Unholy/Assets/Scenes/gang/Scenes/Monster.unity.meta
- Unholy/Assets/Scenes/gang/Scripts.meta
- Unholy/Assets/Scenes/gang/Scripts/MonsterSpawner.cs
- Unholy/Assets/Scenes/gang/Scripts/MonsterSpawner.cs.meta
- Unholy/Assets/Settings/URP-Balanced.asset
- Unholy/Assets/Settings/URP-HighFidelity-Renderer.asset
- Unholy/Assets/Settings/URP-HighFidelity.asset
- Unholy/Assets/Settings/URP-Performant.asset
- Unholy/Assets/UniversalRenderPipelineGlobalSettings.asset
- 목록 1
- 몬스터 스포너 생성 > 삭제 해야 함
- 목록 1
> 몬스터 스포너 생성을 했지만 주제 변경으로 인한 삭제
---
- 쓸데없는 Manager 객체가 존재하진 않는가?
- 불필요한 필드가 존재하진 않는가?
- 모듈화는 잘 되어 있는가?
- 객체 간 결합도는 …
> feat: Create a MosterSpawner

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Animation Controller/PlayerController.controller.meta
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs.meta
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- PlayerAnimation.cs 추가
- PlayerAnimParameter.cs 추가
- PlayerController.cs 수정
- PlayerAnimator 구성
- PlayerAnimation.cs 추가
> Player의 애니메이션 기능만 분리하기 위해 생성하였습니다.
> 현재는 animator parameter 값을 받아 animation으로 전환해주는 ControlAnimation() 메소드가 있습니다.
- PlayerAnimParameter.cs 추가
> Player의 animation parameter 값만 관리하는 스크립트를 추가하였습니다. 
> 모든 Player 관련 parameter는 static을 사용하여 접근이 가능하도록 하였습니다.
> MonoBehaviour를 상속하지 않았기 때문에 component로 사용할 수 없습니다.
- PlayerController.cs 수정
> InitializeInputSystem() : input system event binding을 setting하는 메소드를 추가하고 Awak() 일부 내용을 …
> feat: Player unarmed FSM - movement - walk animation 구현 (#29)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Animation Controller/PlayerController.controller.meta
- Unholy/Assets/Animations/Player/Unarmed/P_UnArm_Sprint-Forward.FBX.meta
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Player unarmed FSM 수정
- Movement sub state machine 수정
- PlayerAnimation.cs 수정
- PlayerAnimParameter.cs 수정
- PlayerController.cs 수정
- PlayerBehaviour.cs 수정
- Player unarmed FSM 수정
> Unarmed 하위에서 Movement가 분리된 상태로 동작할 경우 아래 기술한 문제가 발생하여, Idle에서 Movement로 전이되도록 수정하였습니다.
- Movement sub state machine 수정
> Any State에서 Walk와 Sprint로 연결 시 Walk와 Sprint 사이의 전환이 제대로 동작하지 않는 문제가 발생했습니다.
> 문제를 수정하기 위해 Any State가 아닌 Entry에서 전이되도록 수정하여, Walk와 Sprint 전환을 제대로 동작하도록 수정하였습니다.
- PlayerAnimation.cs 수정
> ControlAnimation() 내부에서 Animation이 Sprint 상태로 전이되도록 …
> feat: Player unarmed FSM - movement - sprint 구현 (#30)

- Unholy/Assets/Animation Controller/Dodge_Controller.controller
- Unholy/Assets/Animation Controller/Dodge_Controller.controller.meta
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
- PlayerInput "Dodge" 추가
- PlayerAnimParameter.cs 변경
- PlayerController.cs 변경
- PlayerBehaviour.cs 변경
- PlayerAnimation.cs 변경
- Dodge_Controller 추가 
- PlayerInput "Dodge" 추가
> Dodge 액션을 실행시킬 수 있는 left control 키를 바인딩 하였습니다.
> left control 키를 누르면 dodge 애니메이션 및 액션이 실행됩니다.
- PlayerAnimParameter.cs 변경
> Dodge animation을 실행시키는 parameter 값들을 추가하였습니다.
- PlayerController.cs 변경
> dodge키(left control) 액션 바인딩을 하였습니다.
> dodge 액션을 실행시킬 때 필요한 현재 회전 값을 저장할 수 있는 rollDirection을 저장하였습니다.
> udpate에서 PlayerDodge 메소드가 실행됩니다.
- PlayerBehaviour.cs 변경
> PlayerDodge(Vector3 lastMoveDirection): dodge 동작을 실제로 실행시키는 메소드입니다.
> dodgePower만큼 player가 바라보는 …
> feat: Player unarmed FSM dodge 구현 (#32)

- Unholy/Assets/Scenes/BT/Ani Crtl/minotaur1_Animator_Controller.controller
- Unholy/Assets/Scenes/BT/BT Test.unity
- Unholy/Assets/Scenes/BT/Script/BossAI.cs
- Unholy/Packages/manifest.json
- Unholy/Packages/packages-lock.json
- Unholy/ProjectSettings/PackageManagerSettings.asset
- Monster(Boss) Behavior Tree build with using fluid behavior tree
- 목록 1 
- Fluid BT를 이용하여 몬스터 BT를 구성함.
- 목록 1
> Fluid behavior tree(custom asset) 을 적용시킴
> Fluid behavior tree 사용법에 따른 moster(boss) behavior tree 에서 전체적인 틀만 잡아둠.
이번 변경과 관련된 이슈가 있다면 아래에 작성해주세요.
- [] #45 
- [] #51 
---
- [코드 컨벤션](https://learn.microsoft.com/ko-kr/dotnet/csharp/fundamentals/co …
> feat: Monster(boss) Behavior Tree Build

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/ExplosiveLLC.meta
- Unholy/Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack FREE.meta
- Unholy/Assets/ExplosiveLLC/RPG Character Mecanim Animation Pack FREE/InputSystem - Requires InputSystem Package.unitypackage.meta
- Unholy/Assets/ExplosiveLLC/Warrior FREE.meta
- Unholy/Assets/ExplosiveLLC/Warrior FREE/InputSystem Support - Requires InputSystem Package.unitypackage.meta
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/ProjectSettings/PackageManagerSettings.asset
- PlayerController.cs 수정
- PlayerAnimation.cs 수정
- PlayerBehaviour.cs 수정
- 불필요한 에셋 폴더 삭제
> AbleToJump, AbleToDodge bool parameter 추가
> Jump가 가능한 상태인지, dodge가 가능한 상태인지를 나타내는 parameter입니다.
> Dodge 애니메이션 전환 조건을 수정하였습니다.
> AbleToDodge가 true 상태일 때 애니메이션이 전환될 수 있도록 조건을 추가하였습니다.
> Jump 애니메이션 전환 조건을 수정하였습니다.
> AbleToJump가 true 상태일 때 애니메이션이 전환될 수 있도록 조건을 추가하였습니다.
- PlayerController.cs 수정
> dodge키가 입력됐을 때 dodge 동작을 수행하는 로직이 변경되었습니다.
> 조건문을 추가하고 dodge 동작을 수행시키는 coroutine을 추가하였습니다.
- PlayerAnimation.cs 수정
> update의 isPlayingJumpAnimation을 삭제하였습니다.
> AbleToJump, AbleToDodge로 …
> bug: Jump - Dodge animation 전환 오류 (#52)

- Unholy/Assets/Animations/Monster/Boss_Track.fbx.meta
- Unholy/Assets/Scenes/BT/Script/BossAI.cs
- Apply animation only for each state in the behavior tree
- 목록 1
- 각 상태마다 동작하는 애니메이션"만" 적용시켰다. 
- 목록 1
> BT 동작을 알아보기 위해 Animator.Play("") 를 이용하여 각 상태에 맞는 애니메이션 동작만 구현함.
이번 변경과 관련된 이슈가 있다면 아래에 작성해주세요.
- [] #45 
---
- 코드 흐름은 …
> feat: Apply each animation in the monster(boss) BT(#51)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- 불필요한 코드 제거
> 이동 중 연속 점프 시 애니메이션 전환 오류를 수정하기 위해, 애니메이션 사이에 트랜지션을 추가하였습니다.
- 불필요한 코드 제거
> 사용되지 않는 불필요한 코드(필드 값 등)를 제거하였습니다.
- #56 
---
- 쓸데없는 Manager 객체가 …
> bug: 이동 중 연속 점프 시 애니메이션 전환 오류 (#56)

- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- 논 타겟팅 카메라 구현
- 타겟팅 카메라 구현
- PlayerController.cs 수정
- PlayerBehaviour.cs 수정
- Camera 속 CinemachineBrain 컴포넌트 수정
- 논 타겟팅 카메라 구현
> Cinemachine의 Freelook Camera를 이용하여 플레이어를 기준으로 이동하고, 플레이어를 추적하는 카메라를 구현하였습니다.
- 타겟팅 카메라 구현
> Cinemachine의 Virtual Camera를 이용하여 플레이어를 기준으로 이동하고, 타겟(몬스터)를 추적하는 카메라를 구현하였습니다.
- PlayerController.cs 수정
> Awake 속 Cursor와 관련된 코드(커서 잠금, 커서 숨김)를 추가하였습니다.
> Cinemachine 카메라 사용 시 캐릭터의 이동과 카메라의 이동 업데이트 속도가 맞지않아 Jitter가 발생하였습니다.
> 이를 고치기 위해 Update를 FixedUpdate로 수정하였습니다.
- PlayerBehaviour.cs 수정
> Header 수정. 필드 값들을 정리하기 위함입니다. …
> feat: Camera Control 구현 (#59)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Materials/Player/Two Hand/2Handed.mat
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
- Unholy/Assets/Scripts/Player/WeaponSwitch.cs
- Unholy/Assets/Scripts/Player/WeaponSwitch.cs.meta
- Unholy/Assets/Scripts/Player/WeaponType.cs
- Unholy/Assets/Scripts/Player/WeaponType.cs.meta
- 스크립트 생성 및 수정
> OneHand 상태를 구현하였습니다.
> OneHand 하위의 Movement와 Jump 하위 상태 머신 생성하였습니다.
- 스크립트 생성 및 수정
> PlayerAnimation.cs 수정 : WeaponSwitch 관련 코드 추가하였습니다.
> PlayerAnimParameter.cs 수정 : WeaponType 추가하였습니다
> PlayerBehaviour.cs 수정 : ~~무의미한 코드(using Types) 추가, 추후 다시 제거할 예정입니다.~~
> PlayerController.cs 수정 : 각 WeaponType에 맞는 키 바인딩 및 코드 추가하였습니다.
> WeaponSwitch.cs 생성 : Weapon Switch에 관한 코드(인덱스 변경 등) 추가하였습니다.
> …
> feat: Player Melee FSM - Jump (#35)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Animations/Player/One Hand/P_One_Attack1.FBX.meta
- Unholy/Assets/Animations/Player/One Hand/P_One_Attack2.FBX.meta
- Unholy/Assets/Animations/Player/One Hand/P_One_Attack3.FBX.meta
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- Unholy/Assets/Scripts/Player/PlayerBehaviour.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
- Unholy/Assets/Scripts/Player/WeaponSwitch.cs
- PlayerController.controller 변경
- WeaponSwitch.cs 변경
- PlayerController.cs 변경
- PlayerAnimPrameter.cs 변경
- PlayerAnimation.cs 변경
- PlayerBehaviour.cs 변경
- 애니메이션 이벤트 추가
- PlayerController.controller 변경
> Attack sub statemachine을 생성하였습니다.
> attack에 관련된 animator parameter를 생성하였습니다.
- WeaponSwitch.cs 변경
> IsWeaponMelee(): player가 현재 지니고 있는 무기가 근거리 무기인지 판단하는 메소드입니다.
> jump attack은 근거리 무기에서만 사용할 수 있으므로 해당 메소드를 추가하였습니다.
- PlayerController.cs 변경
> attack키를 선언해주고 이벤트 바인딩을 했습니다.
> attack를 누르면 공격이 가능하게 하였습니다.
> isAbleComboAttack: combo attack이 가능한 구간에서 attack키의 입력 여부를 알리는 flag 입니다.
- PlayerAnimPrameter.cs 변경
> IsAttack Trigger를 추가하였습니다. …
> feat: Player Melee FSM - Attack (#34)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimation.cs
- PlayerController.controller 변경
- PlayerAnimation.cs 변경
- PlayerController.controller 변경
> dodge 조건을 변경하였습니다.
> animator override controller 사용을 염두해두고 onehand twohand state를 'Melee', 'Range'로 변경하였습니다.
> anystate에서 dodge 전환 후 exit로 탈출하면 unarmed로 전환 되었다가 one hand로 돌아오는 이슈가 있어 exit 대신 melee 혹은 range로 전환되도록 했습니다.
- PlayerAnimation.cs 변경
> dodge 키를 지속적으로 누르면 isDodging 또한 키보드 키를 떼기 전까지 true로 유지되기 때문에 제자리에서 dodge animation이 반복되는 오류가 발생했습니다.
> 따라서 isDodging이 animation parameter에 값을 넘겨준 후 false가 되도록 했습니다.
- dodge 오류 fix
- [#68 
---
코드 리뷰를 어떻게 해야하는지 모르겠다면 아래의 사항을 고려해보세요. 또 [여기](https://blog.banksalad.com/tech/banksalad-code-review-cultu …
> bug: one hand dodge 오류 (#68)

- Unholy/Assets/Animation Controller/MinoController.controller
- Unholy/Assets/Animations/Monster/Boss_BA_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_BA_BackStep.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Combo_Attack_2Hit.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Combo_Attack_3Hit.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Die.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Hit.FBX.meta
- Unholy/Assets/Animations/Monster/Boss_Jump_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Kick_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Normal_Attack1.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Normal_Attack2.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Track.fbx.meta
- Unholy/Assets/Scenes/Monster/Monster.unity
- Unholy/Assets/Scripts/Monster/BehaviorTreebuilderExtensitions.cs
- Unholy/Assets/Scripts/Monster/BehaviorTreebuilderExtensitions.cs.meta
- Unholy/Assets/Scripts/Monster/CustomAction.cs
- Unholy/Assets/Scripts/Monster/MinoController.cs
- 목록 1
- 공격 애니메이션이 끝난 후에 다른 애니메이션으로 동작하게끔 적용.
- 목록 1
> 공격 중에는 애니메이션이 변경되면 안되기에 Continue 상태에서 Success 상태로 변경되게끔함.
- [] #62 
---
- 쓸데없는 Manager 객체가 존재하진 …
> feat: Behavior Tree Rebuild - IsStateEnd(#65)

- Unholy/Assets/Animation Controller/MinoController.controller
- Unholy/Assets/Animations/Monster/Boss_BA_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_BA_BackStep.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Combo_Attack_2Hit.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Combo_Attack_3Hit.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Jump_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Kick_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Normal_Attack1.fbx.meta
- Unholy/Assets/Animations/Monster/Boss_Normal_Attack2.fbx.meta
- Unholy/Assets/Scenes/Monster/Monster.unity
- Unholy/Assets/Scripts/Monster/CustomAction.cs
- Unholy/Assets/Scripts/Monster/MinoController.cs
- Modified to move on to another move after the attack animation is played.
- 목록 1
- 공격 애니메이션 재생 중에는 다른 애니메이션이 재생이 안되게 끔 구현.
- 목록 2
- 기본 공격 4가지가 동작하면 멈추는 현상 수정 완료.
- 목록 1
> CustomAction.cs 파일에서 Animator.Play 메소드 안에 있는 정규화시간 파라미터를 이용하여 애니메이션이 재생 중일 때는 Continue, 애니메이션이 끝난 후에는 Success 반환하였음.
- 목록 2
> 이전에 코드에서는 기본 공격 애니메이션이 한 번 동작하면 다시 동작을 하지 않아 멈췄었는데, 이번 Animator.Play 정규화 작업을 통해 Success 로 반환되게 만들어 애니메이션을 Loop time 채크없이 계속 동작하게끔 수정 완료.
- [] #70 
---
코드 리뷰를 어떻게 해야하는지 모르겠다면 …
> feat: Behavior tree rebuild(#62)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Animation Controller/Upper Body.mask
- Unholy/Assets/Animation Controller/Upper Body.mask.meta
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.cs
- Unholy/Assets/Scripts/Player/PlayerInputs.inputactions
- UpperBody.mask 생성
- PlayerController.cs, PlayerAnimParameter.cs 수정
- UpperBody.mask 생성
> 애니메이터 컨트롤러 속 새로운 레이어(UpperBody)에서 상체만을 덮어씌우기 위해 UpperBody Avatar Mask를 생성하였습니다.
> 상체 애니메이션을 담당하는 새로운 레이어(UpperBody)를 생성하였습니다.
> 추후 방어 등에 사용할 새로운 파라미터 IsRightClick을 bool 값으로 추가하였습니다.
> UpperBody 레이어 속 Defense를 임의로 구현하여 동작을 시각적으로 확인할 수 있도록 하였습니다.
- PlayerController.cs, PlayerAnimParameter.cs 수정
> 우클릭(Defense) 동작과 관련된 코드를 추가하였습니다.
- UpperBody.mask
- ![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/95358325/ee3eabd2-934a-4235-ad94-f870396ba4c4)
- 상체 …
> feat: Player Upper Body FSM (#39)

- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/Player/PlayerAnimParameter.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/AttackBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/ComboAttackBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/DefenseBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/DefenseBehaviour.cs.meta
- Unholy/Assets/Scripts/Player/StateBehaviour/DodgeBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/JumpAttackBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/JumpBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/WeaponSwitchBehaviour.cs
- Unholy/Assets/Scripts/Player/WeaponSwitch.cs
- DefenseBehaviour.cs 추가 및 애니메이션 설정
- Parry 구간 설정
- Magic Number 제거
- 불필요한 주석 제거 
- DefenseBehaviour.cs 추가 및 애니메이션 설정
> 방어 동작에 대한 StateBehaviour를 생성하였습니다.
- Parry 구간 설정
> DefenseBehaviour.cs에서 normalize를 이용해 패링이 작동되는 구간을 설정하였습니다.
- Magic Number 제거
> 모든 플레이어 스크립트의 Magic Number를 제거하였습니다.
- 불필요한 주석 제거 
> 모든 플레이어 스크립트의 불필요한 주석을 제거하였습니다.
> 각 애니메이션의 전이 조건과 상태를 수정하였습니다.
- [] #36 
- [] #19 
- [] #85 
---
- [코드 …
> feat: Player Melee FSM - Defense (#36-1)

- Unholy/Assets/Animation Controller/MinoController.controller
- Unholy/Assets/Animations/Monster/B_Combo_Attack_2Hit.fbx.meta
- Unholy/Assets/Animations/Monster/B_Combo_Attack_3Hit.fbx.meta
- Unholy/Assets/Animations/Monster/B_Jump_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/B_Normal_Attack1.fbx.meta
- Unholy/Assets/Animations/Monster/B_Normal_Attack2.fbx.meta
- Unholy/Assets/Materials/FX.meta
- Unholy/Assets/Materials/FX/Spark.mat
- Unholy/Assets/Materials/FX/Spark.mat.meta
- Unholy/Assets/Prefabs/FX.meta
- Unholy/Assets/Prefabs/FX/ParrySpark.prefab
- Unholy/Assets/Prefabs/FX/ParrySpark.prefab.meta
- Unholy/Assets/Prefabs/FX/WeaponSpark.prefab
- Unholy/Assets/Prefabs/FX/WeaponSpark.prefab.meta
- Unholy/Assets/Prefabs/Monster/minotaur1.prefab
- Unholy/Assets/Prefabs/Player/Player.prefab
- Unholy/Assets/Scenes/Global Volume Profile.asset
- Unholy/Assets/Scenes/Global Volume Profile.asset.meta
- Unholy/Assets/Scenes/Monster/Monster.unity
- Unholy/Assets/Scripts/Monster/MinoController.cs
- Unholy/Assets/Scripts/Player/PlayerAttackCollision.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Settings/URP-HighFidelity.asset
- Unholy/Assets/Shader.meta
- Unholy/Assets/Shader/Distortion.mat
- Unholy/Assets/Shader/Distortion.mat.meta
- Unholy/Assets/Shader/Distortion.shadergraph
- Unholy/Assets/Shader/Distortion.shadergraph.meta
- Boss Weapon Trail
- Player Weapon Effect
- Boss Weapon Trail
> 보스의 무기 트레일을 추가하였습니다.
> 셰이더 그래프를 사용한 왜곡 효과를 주는 매터리얼을 생성하였습니다.
> 생성한 매터리얼을 파티클 시스템에 적용하였습니다.
- Player Weapon Effect
> 파티클을 이용해 무기가 부딪쳤을 때 생성되는 스파크 이펙트를 추가하였습니다.
> 부딪쳤을 때 생성되는 스파크는 무기의 최초 접촉 지점에서 생성되도록 하였습니다.
> 파티클을 이용해 패링 성공 시 생성되는 스파크 이펙트를 추가하였습니다.
- #81 
- #93 
---
- …
> feat: 전투 특수효과 (#81)

- Unholy/Assets/Animation Controller/MinoController.controller
- Unholy/Assets/Prefabs/FX/ParrySpark.prefab
- Unholy/Assets/Prefabs/Monster/minotaur1.prefab
- Unholy/Assets/Scenes/Monster/Monster.unity
- Unholy/Assets/Scripts/Monster/MinoController.cs
- Bug Fixed
- Boss & Particle Prefab Modified
- Boss Script Modified
- Bug Fixed
> 패링 시 패링 파티클이 중첩되어 생성되는 버그가 발생하였습니다.
> 패링 시 생성되는 조건을 곧 바로 초기화하도록 수정하여 해결하였습니다.
- Boss & Particle Prefab Modified
> 보스와 파티클 프리팹을 일부 수정하였습니다.
- Boss Script Modified
> 보스 스크립트를 수정하였습니다.
- #81 
---
- 쓸데없는 Manager 객체가 존재하진 않는가?
- 불필요한 …
> fix: 패링 시 패링 이펙트 중첩 발생 (#106)

- Unholy/Assets/Shader/Door_Distortion.mat
- Unholy/Assets/Shader/Door_Distortion.mat.meta
- Unholy/Assets/Shader/Transparency.mat
- Unholy/Assets/Shader/Transparency.mat.meta
- Field 프리팹 수정
- Shader material 추가
- Field 프리팹 수정
> 큐브 오브젝트를 생성하여 커스텀 쉐이더 적용 후 바닥에 위치하고 Ground 태크를 부착하였습니다.
- Shader material 추가
> 오브젝트를 투명하게 하기 위해 material 을 추가하였습니다.
이번 변경과 관련된 이슈가 있다면 아래에 작성해주세요.
- [] #89 
---
- 쓸데없는 Manager 객체가 존재하진 않는가?
- 불필요한 필드가 존재하진 않는가?
- 모듈화는 잘 되어 있는가?
- 객체 간 결합도는 충분히 낮은가?
- 함수는 하나의 …
> fix: Fix Collider

- Unholy/Assets/Prefabs/FX/Blood.prefab
- Unholy/Assets/Prefabs/FX/Blood.prefab.meta
- Unholy/Assets/Prefabs/Monster/minotaur1.prefab
- Unholy/Assets/Prefabs/Player/Player.prefab
- Unholy/Assets/Scenes/Monster/Monster.unity
- Unholy/Assets/Scripts/Monster/MinoCollider.cs
- Unholy/Assets/Scripts/Player/PlayerAttackCollision.cs
- Unholy/Assets/Shader/Blood.mat
- Unholy/Assets/Shader/Blood.mat.meta
- 보스 및 플레이어 출혈 이펙트 생성
- 플레이어 무기 궤적 생성
- 보스 및 플레이어 프리팹 수정
- 보스 및 플레이어 출혈 이펙트 생성
> 보스 및 플레이어가 피격됐을 때 생성될 출혈 이펙트를 파티클 시스템을 이용해 구현하였습니다.
- 플레이어 무기 궤적 생성
> 보스의 무기 궤적 trail을 참고하여 플레이어의 각 무기 trail을 생성하였습니다.
- 보스 및 플레이어 프리팹을 수정
> 보스 및 플레이어의 컴포넌트 및 하위 오브젝트를 수정하여 프리팹을 저장(수정)하였습니다.
- #110 
- #81 
---
- 쓸데없는 Manager 객체가 …
> feat: 전투 특수효과 (#110)

- Unholy/Assets/Animation Controller/MinoController.controller
- Unholy/Assets/Animation Controller/PlayerController.controller
- Unholy/Assets/Animations/Monster/B_BA_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/B_Jump_Attack.fbx.meta
- Unholy/Assets/Animations/Monster/B_Kick_Attack.fbx.meta
- Unholy/Assets/Prefabs/Monster/minotaur1.prefab
- Unholy/Assets/Scenes/Character.unity
- Unholy/Assets/Scripts/CombatManager.cs
- Unholy/Assets/Scripts/Monster/MinoCollider.cs
- Unholy/Assets/Scripts/Monster/MinoController.cs
- Unholy/Assets/Scripts/Player/PlayerController.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/ComboAttackBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/DamagedBehaviour.cs
- Unholy/Assets/Scripts/Player/StateBehaviour/DeathBehaviour.cs
- Unholy/Assets/Scripts/UI/TitleSceneManager.cs
- Unholy/Assets/Scripts/UI/UIPopUp.cs
- Unholy/Assets/Scripts/UI/UIStatBar.cs
- Unholy/Assets/Settings/URP-Balanced.asset
- Unholy/Assets/Settings/URP-HighFidelity.asset
- Unholy/Assets/Settings/URP-Performant.asset
- #110 의 누락된 내용 추가
- UI 씬 전환 수정
- #110 의 누락된 내용 추가
> 브랜치 생성 후 커밋 푸쉬 과정에서 이전의 내용을 덮어씌우게 되어 누락된 내용을 복구함.
- UI 씬 전환 수정
> GameOver, GameClear 조건 수정
- [] #110 
- [] #94 
---
- …
> fix: CombatManager / _longDefense 삭제 이슈 (#113)
